import ThemeRegistry from '@/customization/theme/ThemeRegistry'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/header/Header'
import Footer from '@/components/layout/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <ThemeRegistry>
        <body className={inter.className + ' min-h-screen flex flex-col'}>
          <Header />
          <section className='flex-grow'>
            {children}
          </section>
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  )
}
